name: Generate Breakout Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todos los días a medianoche
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-breakout-svg
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate-breakout-svg
        uses: lowlighter/metrics@latest
        with:
          filename: breakout.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_breakout: yes
          plugin_breakout_speed: 1.5

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: pacman-output # Aquí se guardará tu Pacman
          target-folder: .
